apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb
data:
  database-name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  database-password: UGlvdF8xMjM=
  database-user: cGlvdHI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: departamento
  labels:
    app: departamento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: departamento
  template:
    metadata:
      labels:
        app: departamento
    spec:
      containers:
      - name: departamento
        image: fabricio211/departamento:3.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: departamento
  labels:
    app: departamento
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: departamento